Repository 100-hours-a-week/5-bigbrother-slimdealz-be, pull requests merged in 2024-08, with the labels that each got.

#9 설정 추가
  build.gradle
  src/main/java/bigbrother/slimdealz/SlimDealzApplication.java
  src/main/java/bigbrother/slimdealz/auth/JWTutil.java
  src/main/java/bigbrother/slimdealz/auth/LoginFilter.java
  src/main/java/bigbrother/slimdealz/config/FCMConfig.java
  src/main/java/bigbrother/slimdealz/controller/CommentController.java
  src/main/java/bigbrother/slimdealz/controller/ProductController.java
  src/main/java/bigbrother/slimdealz/controller/SearchController.java
  src/main/java/bigbrother/slimdealz/controller/User/AuthController.java
  src/main/java/bigbrother/slimdealz/controller/User/BookmarkController.java
  src/main/java/bigbrother/slimdealz/controller/User/NotificationController.java
  src/main/java/bigbrother/slimdealz/dto/BookmarkDto.java
  src/main/java/bigbrother/slimdealz/dto/CommentDto.java
  src/main/java/bigbrother/slimdealz/dto/NotificationDto.java
  src/main/java/bigbrother/slimdealz/dto/ProductDto.java
  src/main/java/bigbrother/slimdealz/dto/SearchDto.java
  src/main/java/bigbrother/slimdealz/dto/UserDto.java
  src/main/java/bigbrother/slimdealz/entity/Bookmark.java
  src/main/java/bigbrother/slimdealz/entity/Comment.java
  src/main/java/bigbrother/slimdealz/entity/Notification.java
  src/main/java/bigbrother/slimdealz/entity/Product.java
  src/main/java/bigbrother/slimdealz/entity/SearchKeyword.java
  src/main/java/bigbrother/slimdealz/entity/User.java
  src/main/java/bigbrother/slimdealz/exception/CustomException.java
  src/main/java/bigbrother/slimdealz/exception/CustomExceptionHandler.java
  src/main/java/bigbrother/slimdealz/repository/CommentRepository.java
  src/main/java/bigbrother/slimdealz/repository/ProductRepository.java
  src/main/java/bigbrother/slimdealz/repository/SearchKeywordRepository.java
  src/main/java/bigbrother/slimdealz/repository/User/BookmarkRepository.java
  src/main/java/bigbrother/slimdealz/repository/User/NotificationRepository.java
  src/main/java/bigbrother/slimdealz/repository/User/UserRepository.java
  src/main/java/bigbrother/slimdealz/service/CommentService.java
  src/main/java/bigbrother/slimdealz/service/ProductService.java
  src/main/java/bigbrother/slimdealz/service/PythonCrawlerService.java
  src/main/java/bigbrother/slimdealz/service/SearchService.java
  src/main/java/bigbrother/slimdealz/service/User/AuthService.java
  src/main/java/bigbrother/slimdealz/service/User/BookmarkService.java
  src/main/java/bigbrother/slimdealz/service/User/NotificationService.java
  src/main/python/crawler/__init__.py
  src/main/python/crawler/comment_scrapper.py
  src/main/python/crawler/price_update.py
  src/main/python/crawler/product_crawler.py
  src/main/python/scripts/run_crawler.py
  src/main/python/utils/__init__.py
  src/main/python/utils/parser.py
  src/main/python/utils/storage_handler.py
Labels: 제안

#11 설정 변경
  .gitignore
  build.gradle
  src/main/java/bigbrother/slimdealz/SlimDealzApplication.java
  src/main/java/bigbrother/slimdealz/config/EnvConfig.java
  src/main/java/bigbrother/slimdealz/config/RedisConfig.java
  src/main/java/bigbrother/slimdealz/config/WebConfig.java
  src/main/java/bigbrother/slimdealz/service/PythonCrawlerService.java
  src/main/python/crawler/__init__.py
  src/main/python/crawler/comment_scrapper.py
  src/main/python/crawler/price_update.py
  src/main/python/crawler/product_crawler.py
  src/main/python/scripts/run_crawler.py
  src/main/python/utils/__init__.py
  src/main/python/utils/parser.py
  src/main/python/utils/storage_handler.py
  src/main/resources/application.yml
Labels: 제안

#19 Feat: 검색 기능
  build.gradle
  src/main/java/bigbrother/slimdealz/SlimDealzApplication.java
  src/main/java/bigbrother/slimdealz/config/QuerydslConfig.java
  src/main/java/bigbrother/slimdealz/config/SecurityConfig.java
  src/main/java/bigbrother/slimdealz/config/WebConfig.java
  src/main/java/bigbrother/slimdealz/controller/ProductController.java
  src/main/java/bigbrother/slimdealz/dto/ProductDto.java
  src/main/java/bigbrother/slimdealz/entity/BaseEntity.java
  src/main/java/bigbrother/slimdealz/entity/Product.java
  src/main/java/bigbrother/slimdealz/repository/Product/ProductRepository.java
  src/main/java/bigbrother/slimdealz/repository/Product/ProductRepositoryCustom.java
  src/main/java/bigbrother/slimdealz/repository/Product/ProductRepositoryImpl.java
  src/main/java/bigbrother/slimdealz/repository/ProductRepository.java
  src/main/java/bigbrother/slimdealz/service/ProductService.java
Labels: 제안

#20 메인 페이지 : 오늘의 최저가
  build.gradle
  src/main/java/bigbrother/slimdealz/controller/ProductController.java
  src/main/java/bigbrother/slimdealz/dto/PriceDto.java
  src/main/java/bigbrother/slimdealz/dto/PriceHistoryDto.java
  src/main/java/bigbrother/slimdealz/dto/ProductConverter.java
  src/main/java/bigbrother/slimdealz/dto/ProductDto.java
  src/main/java/bigbrother/slimdealz/entity/Product.java
  src/main/java/bigbrother/slimdealz/entity/product/Price.java
  src/main/java/bigbrother/slimdealz/entity/product/PriceHistory.java
  src/main/java/bigbrother/slimdealz/entity/product/Product.java
  src/main/java/bigbrother/slimdealz/entity/product/Vendor.java
  src/main/java/bigbrother/slimdealz/repository/Product/PriceHistoryRepository.java
  src/main/java/bigbrother/slimdealz/repository/Product/PriceRepository.java
  src/main/java/bigbrother/slimdealz/repository/Product/ProductRepository.java
  src/main/java/bigbrother/slimdealz/repository/Product/ProductRepositoryCustom.java
  src/main/java/bigbrother/slimdealz/repository/Product/ProductRepositoryImpl.java
  src/main/java/bigbrother/slimdealz/repository/Product/VendorRepository.java
  src/main/java/bigbrother/slimdealz/service/ProductService.java
  src/main/resources/application.yml
Labels: 제안

#21 Feat: 검색, 오늘의 최저가 기능 구현
  build.gradle
  src/main/java/bigbrother/slimdealz/SlimDealzApplication.java
  src/main/java/bigbrother/slimdealz/config/QuerydslConfig.java
  src/main/java/bigbrother/slimdealz/config/SecurityConfig.java
  src/main/java/bigbrother/slimdealz/config/WebConfig.java
  src/main/java/bigbrother/slimdealz/controller/ProductController.java
  src/main/java/bigbrother/slimdealz/dto/PriceDto.java
  src/main/java/bigbrother/slimdealz/dto/PriceHistoryDto.java
  src/main/java/bigbrother/slimdealz/dto/ProductConverter.java
  src/main/java/bigbrother/slimdealz/dto/ProductDto.java
  src/main/java/bigbrother/slimdealz/entity/BaseEntity.java
  src/main/java/bigbrother/slimdealz/entity/Product.java
  src/main/java/bigbrother/slimdealz/entity/product/Price.java
  src/main/java/bigbrother/slimdealz/entity/product/PriceHistory.java
  src/main/java/bigbrother/slimdealz/entity/product/Product.java
  src/main/java/bigbrother/slimdealz/entity/product/Vendor.java
  src/main/java/bigbrother/slimdealz/repository/Product/PriceHistoryRepository.java
  src/main/java/bigbrother/slimdealz/repository/Product/PriceRepository.java
  src/main/java/bigbrother/slimdealz/repository/Product/ProductRepository.java
  src/main/java/bigbrother/slimdealz/repository/Product/ProductRepositoryCustom.java
  src/main/java/bigbrother/slimdealz/repository/Product/ProductRepositoryImpl.java
  src/main/java/bigbrother/slimdealz/repository/Product/VendorRepository.java
  src/main/java/bigbrother/slimdealz/repository/ProductRepository.java
  src/main/java/bigbrother/slimdealz/service/ProductService.java
  src/main/resources/application.yml
Labels: 제안

#24 :bug: Fix : 경로 수정
  src/main/java/bigbrother/slimdealz/repository/Product/ProductRepositoryImpl.java
Labels: 버그-심각

#27 상품 상세 페이지 내의 상품 정보 영역
  .gradle/8.8/checksums/checksums.lock
  .gradle/8.8/checksums/md5-checksums.bin
  .gradle/8.8/checksums/sha1-checksums.bin
  .gradle/8.8/executionHistory/executionHistory.bin
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileHashes/fileHashes.bin
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/8.8/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  build/classes/java/main/bigbrother/slimdealz/SlimDealzApplication.class
  build/classes/java/main/bigbrother/slimdealz/auth/JWTFilter.class
  build/classes/java/main/bigbrother/slimdealz/config/SecurityConfig.class
  build/classes/java/main/bigbrother/slimdealz/config/WebConfig.class
  build/classes/java/main/bigbrother/slimdealz/controller/ProductController.class
  build/classes/java/main/bigbrother/slimdealz/dto/ProductDto.class
  build/classes/java/main/bigbrother/slimdealz/entity/Product.class
  build/classes/java/main/bigbrother/slimdealz/repository/ProductRepository.class
  build/classes/java/main/bigbrother/slimdealz/service/ProductService.class
  build/resources/main/application.yml
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/bigbrother/slimdealz/auth/JWTFilter.java
  src/main/java/bigbrother/slimdealz/controller/ProductController.java
  src/main/java/bigbrother/slimdealz/repository/Product/ProductRepositoryCustom.java
  src/main/java/bigbrother/slimdealz/repository/Product/ProductRepositoryImpl.java
  src/main/java/bigbrother/slimdealz/service/ProductService.java
  src/main/resources/application.yml
Labels: 제안

#28 카테고리별 상품 목록 API
  src/main/java/bigbrother/slimdealz/controller/ProductController.java
  src/main/java/bigbrother/slimdealz/repository/Product/ProductRepositoryCustom.java
  src/main/java/bigbrother/slimdealz/repository/Product/ProductRepositoryImpl.java
  src/main/java/bigbrother/slimdealz/service/ProductService.java
Labels: 제안

#32 에러 수정
  build.gradle
  src/main/java/bigbrother/slimdealz/controller/ProductController.java
  src/main/java/bigbrother/slimdealz/dto/VendorDto.java
  src/main/java/bigbrother/slimdealz/repository/Product/PriceHistoryRepository.java
  src/main/java/bigbrother/slimdealz/repository/Product/PriceRepository.java
  src/main/java/bigbrother/slimdealz/repository/Product/ProductRepository.java
  src/main/java/bigbrother/slimdealz/repository/Product/VendorRepository.java
  src/main/resources/application.yml
Labels: 버그-일반

#35 설정 변경
  src/main/java/bigbrother/slimdealz/repository/Product/PriceHistoryRepository.java
  src/main/java/bigbrother/slimdealz/repository/Product/PriceRepository.java
  src/main/java/bigbrother/slimdealz/repository/Product/ProductRepository.java
  src/main/java/bigbrother/slimdealz/repository/Product/VendorRepository.java
  src/main/java/bigbrother/slimdealz/repository/User/MemberRepository.java
  src/main/resources/application.yml
Labels: 버그-일반

#45 무한 스크롤 응답 추가
  .github/workflows/backend-cd.yml
  .idea/.gitignore
  src/main/java/bigbrother/slimdealz/SlimDealzApplication.java
  src/main/java/bigbrother/slimdealz/config/AppConfig.java
  src/main/java/bigbrother/slimdealz/config/EnvConfig.java
  src/main/java/bigbrother/slimdealz/controller/ProductController.java
  src/main/java/bigbrother/slimdealz/controller/User/KakaoAuthController.java
  src/main/java/bigbrother/slimdealz/repository/Product/ProductRepositoryCustom.java
  src/main/java/bigbrother/slimdealz/repository/Product/ProductRepositoryImpl.java
  src/main/java/bigbrother/slimdealz/service/ProductService.java
  src/main/resources/application.yml
Labels: 제안

#51 판매처 리스트 API 개발
  src/main/java/bigbrother/slimdealz/controller/ProductController.java
  src/main/java/bigbrother/slimdealz/dto/ProductDto.java
  src/main/java/bigbrother/slimdealz/entity/product/Product.java
  src/main/java/bigbrother/slimdealz/repository/Product/ProductRepositoryCustom.java
  src/main/java/bigbrother/slimdealz/repository/Product/ProductRepositoryImpl.java
  src/main/java/bigbrother/slimdealz/service/ProductService.java
Labels: 제안

#63 상품중 랜덤으로 10개 추천
  .gitignore
  build.gradle
  src/main/java/bigbrother/slimdealz/config/EnvConfig.java
  src/main/java/bigbrother/slimdealz/config/S3Config.java
  src/main/java/bigbrother/slimdealz/controller/ImageController.java
  src/main/java/bigbrother/slimdealz/controller/ProductController.java
  src/main/java/bigbrother/slimdealz/controller/User/BookmarkController.java
  src/main/java/bigbrother/slimdealz/controller/User/KakaoAuthController.java
  src/main/java/bigbrother/slimdealz/controller/User/MemberController.java
  src/main/java/bigbrother/slimdealz/dto/JwtRequestDto.java
  src/main/java/bigbrother/slimdealz/dto/NotificationDto.java
  src/main/java/bigbrother/slimdealz/dto/product/PriceDto.java
  src/main/java/bigbrother/slimdealz/dto/product/PriceHistoryDto.java
  src/main/java/bigbrother/slimdealz/dto/product/ProductConverter.java
  src/main/java/bigbrother/slimdealz/dto/product/ProductDto.java
  src/main/java/bigbrother/slimdealz/dto/product/VendorDto.java
  src/main/java/bigbrother/slimdealz/dto/user/BookmarkDto.java
  src/main/java/bigbrother/slimdealz/dto/user/BookmarkProductPriceDto.java
  src/main/java/bigbrother/slimdealz/dto/user/JwtRequestDto.java
  src/main/java/bigbrother/slimdealz/dto/user/MemberDTO.java
  src/main/java/bigbrother/slimdealz/dto/user/MemberUpdateDTO.java
  src/main/java/bigbrother/slimdealz/dto/user/NotificationDto.java
  src/main/java/bigbrother/slimdealz/exception/CustomErrorCode.java
  src/main/java/bigbrother/slimdealz/repository/Product/ProductRepositoryCustom.java
  src/main/java/bigbrother/slimdealz/repository/Product/ProductRepositoryImpl.java
  src/main/java/bigbrother/slimdealz/service/ProductService.java
  src/main/java/bigbrother/slimdealz/service/S3Service.java
  src/main/java/bigbrother/slimdealz/service/User/BookmarkService.java
  src/main/java/bigbrother/slimdealz/service/User/MemberService.java
  src/main/resources/application.yml
  src/test/java/bigbrother/slimdealz/SlimDealzApplicationTests.java
Labels: 제안

#64 s3 이미지 불러오기 로직 수정
  src/main/java/bigbrother/slimdealz/config/S3Config.java
  src/main/java/bigbrother/slimdealz/controller/ImageController.java
  src/main/java/bigbrother/slimdealz/controller/ProductController.java
  src/main/java/bigbrother/slimdealz/repository/Product/ProductRepositoryCustom.java
  src/main/java/bigbrother/slimdealz/repository/Product/ProductRepositoryImpl.java
  src/main/java/bigbrother/slimdealz/service/ProductService.java
  src/main/java/bigbrother/slimdealz/service/S3Service.java
  src/main/resources/application.yml
Labels: 제안

#69 이미지 정보 추가
  src/main/java/bigbrother/slimdealz/controller/ProductController.java
  src/main/java/bigbrother/slimdealz/dto/product/ProductDto.java
  src/main/java/bigbrother/slimdealz/service/ProductService.java
Labels: 제안

#73 컬럼 값이 error인 경우 예외 처리 추가
  src/main/java/bigbrother/slimdealz/repository/Product/VendorRepository.java
  src/main/java/bigbrother/slimdealz/service/ProductService.java
Labels: 버그-일반

#76 데이터 날짜별 조회 기능 추가
  src/main/java/bigbrother/slimdealz/entity/BaseEntity.java
  src/main/java/bigbrother/slimdealz/entity/product/Price.java
  src/main/java/bigbrother/slimdealz/repository/Product/ProductRepositoryImpl.java
Labels: 제안

#77 sentry, cors 설정 추가, s3 이미지 불러오기
  .gitignore
  build.gradle
  src/main/java/bigbrother/slimdealz/config/EnvConfig.java
  src/main/java/bigbrother/slimdealz/config/S3Config.java
  src/main/java/bigbrother/slimdealz/config/WebConfig.java
  src/main/java/bigbrother/slimdealz/controller/ImageController.java
  src/main/java/bigbrother/slimdealz/controller/ProductController.java
  src/main/java/bigbrother/slimdealz/controller/User/BookmarkController.java
  src/main/java/bigbrother/slimdealz/controller/User/KakaoAuthController.java
  src/main/java/bigbrother/slimdealz/controller/User/MemberController.java
  src/main/java/bigbrother/slimdealz/dto/JwtRequestDto.java
  src/main/java/bigbrother/slimdealz/dto/NotificationDto.java
  src/main/java/bigbrother/slimdealz/dto/product/PriceDto.java
  src/main/java/bigbrother/slimdealz/dto/product/PriceHistoryDto.java
  src/main/java/bigbrother/slimdealz/dto/product/ProductConverter.java
  src/main/java/bigbrother/slimdealz/dto/product/ProductDto.java
  src/main/java/bigbrother/slimdealz/dto/product/VendorDto.java
  src/main/java/bigbrother/slimdealz/dto/user/BookmarkDto.java
  src/main/java/bigbrother/slimdealz/dto/user/BookmarkProductPriceDto.java
  src/main/java/bigbrother/slimdealz/dto/user/JwtRequestDto.java
  src/main/java/bigbrother/slimdealz/dto/user/MemberDTO.java
  src/main/java/bigbrother/slimdealz/dto/user/MemberUpdateDTO.java
  src/main/java/bigbrother/slimdealz/dto/user/NotificationDto.java
  src/main/java/bigbrother/slimdealz/entity/BaseEntity.java
  src/main/java/bigbrother/slimdealz/entity/product/Price.java
  src/main/java/bigbrother/slimdealz/exception/CustomErrorCode.java
  src/main/java/bigbrother/slimdealz/repository/Product/ProductRepositoryCustom.java
  src/main/java/bigbrother/slimdealz/repository/Product/ProductRepositoryImpl.java
  src/main/java/bigbrother/slimdealz/repository/Product/VendorRepository.java
  src/main/java/bigbrother/slimdealz/service/ProductService.java
  src/main/java/bigbrother/slimdealz/service/S3Service.java
  src/main/java/bigbrother/slimdealz/service/User/BookmarkService.java
  src/main/java/bigbrother/slimdealz/service/User/MemberService.java
  src/main/resources/application.yml
  src/test/java/bigbrother/slimdealz/SlimDealzApplicationTests.java
Labels: 버그-일반

#75 Feat: 북마크 삭제/추가 구현
  .github/workflows/backend-cd.yml~upstream_develop
  .gitignore
  src/main/java/bigbrother/slimdealz/config/EnvConfig.java~upstream_develop
  src/main/java/bigbrother/slimdealz/config/SecurityConfig.java
  src/main/java/bigbrother/slimdealz/config/WebConfig.java
  src/main/java/bigbrother/slimdealz/controller/ProductController.java
  src/main/java/bigbrother/slimdealz/controller/User/BookmarkController.java
  src/main/java/bigbrother/slimdealz/controller/User/KakaoAuthController.java
  src/main/java/bigbrother/slimdealz/controller/User/LoginController.java
  src/main/java/bigbrother/slimdealz/controller/User/MemberController.java
  src/main/java/bigbrother/slimdealz/dto/user/BookmarkProductPriceDto.java
  src/main/java/bigbrother/slimdealz/dto/user/MemberDTO.java
  src/main/java/bigbrother/slimdealz/entity/Member.java
  src/main/java/bigbrother/slimdealz/entity/product/Product.java
  src/main/java/bigbrother/slimdealz/repository/Product/ProductRepository.java
  src/main/java/bigbrother/slimdealz/repository/User/BookmarkRepository.java
  src/main/java/bigbrother/slimdealz/service/User/BookmarkService.java
  src/main/java/bigbrother/slimdealz/service/User/MemberService.java
Labels: 제안
